@startuml
digraph dfd{
	node[shape=record]
Deal [label="{<f0> Deal|<f1> id: ru.vood.dmgen.datamodel.valueClasses.DealId\nnoFKAndUk: NoFKAndUk\noneOfDto: OneOfDto\ndealOneData: DealOneData }" shape=Mrecord color=Red];
DealOneData [label="{<f0> DealOneData|<f1> dealId: ru.vood.dmgen.datamodel.valueClasses.DealId\none: kotlin.String }" shape=Mrecord color=Green];
NoFKAndUk [label="{<f0> NoFKAndUk|<f1> dealId: ru.vood.dmgen.datamodel.valueClasses.DealId }" shape=Mrecord color=Green];
OneOfDto [label="{<f0> OneOfDto|<f1> dealId: ru.vood.dmgen.datamodel.valueClasses.DealId }" shape=Mrecord color=Yellow];

DealOneData -> Deal[ color=Red];
NoFKAndUk -> Deal[ color=Indigo];
OneOfDto -> Deal[ color=Red];

}
@enduml
