@startuml
digraph dfd{
	node[shape=record]
Deal [label="{<f0> Deal|<f1> id: id\ns: s\nsn: sn?\nb: b\nbn: bn? }" shape=Mrecord color=Red];
DealExtendData [label="{<f0> DealExtendData|<f1> dealId: dealId\nextendData: extendData }" shape=Mrecord color=Red];
DealOneData [label="{<f0> DealOneData|<f1> dealId: dealId\none: one? }" shape=Mrecord color=Green];
DealOneOfData [label="{<f0> DealOneOfData|<f1> dealId: dealId }" shape=Mrecord color=Yellow];
DealParamOneToOne [label="{<f0> DealParamOneToOne|<f1> dealId: dealId\nparamDate: paramDate }" shape=Mrecord color=Green];
DealParamOneToOneOptional [label="{<f0> DealParamOneToOneOptional|<f1> dealId: dealId\nparamDate: paramDate }" shape=Mrecord color=Green];
DealParamSet [label="{<f0> DealParamSet|<f1> dealId: dealId\nid: id\nparamDate: paramDate }" shape=Mrecord color=Green];
DealTwoData [label="{<f0> DealTwoData|<f1> dealId: dealId\ntwo: two? }" shape=Mrecord color=Green];
InnerToDealParamOneToOne [label="{<f0> InnerToDealParamOneToOne|<f1> dealId: dealId\nparamDate: paramDate }" shape=Mrecord color=Green];
OneOfDto [label="{<f0> OneOfDto|<f1> dealId: dealId\nparamDate: paramDate }" shape=Mrecord color=Red];
Product [label="{<f0> Product|<f1> id: id\ndealId: dealId\notherSystemProductId: otherSystemProductId\nproductName: productName\ninn: inn?\nln: ln?\ndn: dn?\nfn: fn?\nbn: bn?\nisdsdd: isdsdd?\nl: l\nd: d\nf: f\nb: b }" shape=Mrecord color=Red];
ProductPayments [label="{<f0> ProductPayments|<f1> productId: productId\ndealId: dealId\nid: id\nsumma: summa\nnoRelationData: noRelationData }" shape=Mrecord color=Red];

DealExtendData -> Deal[ color=Red];
DealOneData -> DealOneOfData[ color=Red];
DealOneOfData -> OneOfDto[ color=Red];
DealParamOneToOneOptional -> Deal[ color=Green];
DealParamOneToOne -> Deal[ color=Red];
DealParamSet -> Deal[ color=Indigo];
DealTwoData -> DealOneOfData[ color=Red];
InnerToDealParamOneToOne -> DealParamOneToOne[ color=Red];
OneOfDto -> Deal[ color=Green];
ProductPayments -> Deal[ color=Indigo];
ProductPayments -> Product[ color=Green];
Product -> Deal[ color=Indigo];

}
@enduml
